from blackbox_repository.blackbox import Blackbox, from_function
from blackbox_repository.blackbox_offline import BlackboxOffline, deserialize
from blackbox_repository.repository import load, blackbox_list
from blackbox_repository.blackbox_surrogate import add_surrogate
