name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: 
      labels: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install .[extra] --upgrade pip
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82,F401 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Black code formatter
      run: |
        # Based on the code from githooks/pre-commit
        # runs Black on all python files committed in git
        echo "Running black: https://github.com/psf/black"
        echo "Black should pass before commit! If this fails, run the command on the next line to fix the errors, then commit the changes"
        echo "git ls-files | grep "\.py$" |  xargs black"
        echo "Run 'pip install .[extra,dev]' if you do not have Black installed locally."
        git ls-files | grep "\.py$" |  xargs black --check
